version: '3.7'
services:
  backend:
    image: my-backend-image:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    image: my-frontend-image:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8052:80"
    depends_on:
      - backend